/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './js/**/*.js',
  ],
  safelist: [
    'hidden', 'block', 'flex', 'inline-flex', 'grid', 'inline-block',
    'md:flex', 'md:hidden', 'md:block', 'md:inline-flex',
    'md:grid-cols-2', 'md:grid-cols-3',
    'md:gap-6', 'md:gap-8',
    'md:px-6', 'md:px-8',
    'md:py-24', 'md:pb-32', 'md:pb-48',
    'md:pt-20', 'md:pt-40',
    'md:mt-0', 'md:mt-8',
    'md:text-7xl', 'md:text-6xl', 'md:text-5xl', 'md:text-xl', 'md:text-base', 'md:text-lg',
    'md:h-16', 'md:h-6', 'md:h-3', 'md:h-4',
    'md:w-32',
    'md:top-8',
    'md:mb-6', 'md:mb-8', 'md:mb-10', 'md:mb-16', 'md:mb-20',
    'sm:text-5xl', 'sm:text-lg', 'sm:flex-row', 'sm:w-auto', 'sm:px-0',
    'md:flex-row', 'flex-col',
    'md:col-span-2',
    'md:p-8', 'md:p-10', 'md:p-6',
    'md:w-14', 'md:h-14', 'md:w-7', 'md:h-7',
    'md:text-2xl',
    'md:rounded-2xl', 'md:rounded-xl', 'md:rounded-b-lg',
    'md:blur-[120px]', 'md:blur-[150px]',
    'md:h-[500px]', 'md:h-[120%]',
    'md:w-[800px]', 'md:w-[120%]', 'md:w-[1000px]', 'md:h-[1000px]',
    'md:text-4xl',
    'md:mb-12',
    'md:px-6', 'md:pb-6',
    'md:text-base',
    'opacity-0', 'opacity-100',
    'pointer-events-none', 'pointer-events-auto',
    'translate-y-0', '-translate-y-4', 'translate-y-16', '-translate-y-12',
    'translate-x-0', '-translate-x-12', 'translate-x-12',
    '-translate-x-1/2', '-translate-y-1/2',
    'scale-100', 'scale-95', 'scale-90',
    'blur-0', 'blur-lg',
    'fixed', 'absolute', 'relative', 'inset-0',
    'z-40', 'z-50',
    'backdrop-blur-md', 'backdrop-blur-xl', 'backdrop-blur-2xl',
    'bg-black/40', 'bg-black/60',
    'rounded-2xl', 'rounded-full', 'rounded-xl', 'rounded-3xl',
    'shadow-2xl', 'shadow-xl', 'shadow-lg',
    'overflow-hidden', 'overflow-y-auto', 'overflow-x-hidden',
    'max-h-[80vh]',
    'animate-float', 'animate-ping', 'animate-pulse-slow',
    'will-change-transform',
    'leading-[0]', 'leading-[1.1]',
    'tracking-tighter', 'tracking-tight', 'tracking-wider', 'tracking-widest',
    'text-transparent',
    'bg-clip-text',
    'bg-gradient-to-b', 'bg-gradient-to-r', 'bg-gradient-to-br', 'bg-gradient-to-tr',
    'from-white', 'to-white/60',
    'from-gray-900', 'via-gray-900', 'to-gray-500',
    'border-white/5', 'border-white/10', 'border-white/20',
    'text-brand-500',
    'bg-brand-500', 'bg-brand-500/10', 'bg-brand-500/15', 'bg-brand-500/20', 'bg-brand-500/30',
    'text-brand-500/30',
    'hover:text-white', 'hover:bg-white/10', 'hover:border-white/20',
    'hover:opacity-90', 'hover:shadow-2xl',
    'active:scale-95', 'active:bg-white/5',
    'group', 'group-hover:text-white', 'group-hover:opacity-100',
    'transition-all', 'transition-colors', 'transition-opacity',
    'duration-300', 'duration-500',
    'whitespace-nowrap',
    'shrink-0',
    'flex-grow',
    'items-stretch',
    'min-h-[380px]', 'md:min-h-[420px]', 'min-h-[400px]',
    'aspect-[16/10]',
    'object-cover', 'object-top', 'object-contain',
    'selection:bg-brand-500/30',
    'scroll-smooth',
    '-mr-2', '-rotate-90',
    'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-6', 'gap-8',
    'space-y-3', 'space-y-4',
    'w-full', 'h-full',
    'inset-x-0',
    'top-0', 'top-4', 'top-6', 'top-20',
    'left-0', 'left-4', 'right-0', 'right-4',
    'bottom-0',
    '-top-3.5',
    'text-center', 'text-left',
    'md:text-left',
    'fill-current',
    'line-through', 'decoration-gray-500',
    'uppercase', 'lowercase',
    'font-sans',
    {
      pattern: /^(p|m|px|py|pt|pb|pl|pr|mx|my|mt|mb|ml|mr)-(0|0\.5|1|1\.5|2|3|4|5|6|8|10|12|16|24|32)$/,
    },
    {
      pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl)$/,
    },
    {
      pattern: /^font-(normal|medium|semibold|bold|extrabold|black)$/,
    },
    {
      pattern: /^(w|h)-(3|4|5|6|8|10|12|14|16|20|24|32|auto)$/,
    },
    {
      pattern: /^(rounded)-(none|sm|md|lg|xl|2xl|3xl|full)$/,
    },
    {
      pattern: /^text-(white|black|gray-[0-9]+|green-[0-9]+|emerald-[0-9]+|orange-[0-9]+|blue-[0-9]+|red-[0-9]+)$/,
    },
    {
      pattern: /^bg-(white|black|transparent|gray-[0-9]+|green-[0-9]+|emerald-[0-9]+)$/,
    },
    {
      pattern: /^border-(white|gray-[0-9]+)$/,
    },
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#00F0FF',
          50: '#e0fcff',
          100: '#b3f8ff',
          200: '#80f4ff',
          300: '#4df0ff',
          400: '#26ecff',
          500: '#00F0FF',
          600: '#00d6e6',
          700: '#00bccc',
          800: '#00a3b3',
          900: '#008599',
        }
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        }
      }
    }
  },
  plugins: [],
}
